if ( SERVER ) then
resource.AddWorkshop( "391383735" );
resource.AddWorkshop( "366580133" );
resource.AddWorkshop( "216408135" );
resource.AddWorkshop( "348376962" );
resource.AddWorkshop( "131828004" );
resource.AddWorkshop( "160059572" );
resource.AddWorkshop( "116797740" );
resource.AddWorkshop( "171925253" );
resource.AddWorkshop( "325884882" );
resource.AddWorkshop( "295788137" );
resource.AddWorkshop( "421942286" );
resource.AddWorkshop( "311396909" );

resource.AddFile( "sound/taunts/avispate_re_weon.mp3" );
resource.AddFile( "sound/taunts/uyui_2.mp3" );
resource.AddFile( "sound/taunts/uyui.mp3" );
resource.AddFile( "sound/taunts/chupese_el_pico.mp3" );
resource.AddFile( "sound/taunts/callate_vieja_culia.mp3" );
resource.AddFile( "sound/taunts/weona_que_brutal.mp3" );
resource.AddFile( "sound/taunts/Smokemon.mp3" );
resource.AddFile( "sound/taunts/mi_mano.mp3" );
resource.AddFile( "sound/taunts/un_choripan.mp3" );
resource.AddFile( "sound/taunts/tan_helao.mp3" );
resource.AddFile( "sound/taunts/trini.mp3" );
resource.AddFile( "sound/taunts/un_manjar.mp3" );
resource.AddFile( "sound/taunts/flaite.mp3" );
resource.AddFile( "sound/taunts/200_100_lucas.mp3" );
resource.AddFile( "sound/taunts/terrible_brijido.mp3" );
resource.AddFile( "sound/taunts/terrible_brijido2.mp3" );
resource.AddFile( "sound/taunts/para_la_wea_logi_culiao.mp3" );
resource.AddFile( "sound/taunts/falazia_oe.mp3" );
resource.AddFile( "sound/taunts/aweonao_cristian.mp3" );
resource.AddFile( "sound/taunts/loh_peshoh.mp3" );
resource.AddFile( "sound/taunts/marepoto.mp3" );
resource.AddFile( "sound/taunts/una_olla.mp3" );
end;
